version: '3.9'

services:

  dm_postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - dm
  dm_redis:
    image: "redis:latest"
    container_name: redis
    hostname: redis
    volumes:
      - redisDB:/var/lib/data
    networks:
      - dm
    ports:
      - "6378:6379"
  app:
    build: .
    container_name: app
    image: app
    environment:
      - ENV
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "8082:8082"
    depends_on:
      - dm_postgres
      - dm_redis
    networks:
      - dm

networks:
  dm:
volumes:
  pg-data:
  redisDB: